### PR TITLE
Make sure render can be called after a value has been updated

### PR DESCRIPTION
**Pull request by exussum12**
relates to #361. Added some tests. All passing on Chrome and Firefox, Not tested others

### CODE REVIEW

**Comment by Blasz** [comment]
So this PR was never landed?

**Comment by exussum12** [comment]
No. Sorry I accidently deleted the branch and then re opened the pull request. I've been using the code here for about a year and as far as I can sss its ok

**Comment by exussum12** [comment]
Oops didn't re open. I will re open after I push the branch

**Comment by exussum12** [comment]
Branch is back

**Comment by powmedia** [comment]
Thanks @exussum12

**Comment by Blasz** [comment]
Awesome.

**Comment by fonji** [comment]
:+1:

**Comment by Blasz** [comment]
What's the policy on when the distribution folders should be updated. Only on tagged version releases or should they be rebuilt with/after pull requests as well?

**Comment by philfreo** [comment]
Just update `src` here -- `distribution` will get auto-built once it's merged in. I haven't had a chance to look at this yet but maybe @powmedia has. 

@exussum12 does the test I wrote in https://github.com/powmedia/backbone-forms/issues/378#issue-33010044 pass in this branch?

**Comment by gebrits** [comment]
Just to ping: did this or another pull with similar functionality ever made it? Still looking for the best way to be able to call render() multiple times.

**Pull request merged**
