### PR TITLE
Update bootstrap3.js

### PR DESCRIPTION
**Pull request by unti1x**
fixed classname for checkboxes list

### CODE REVIEW

**Comment by exussum12** [comment]
@unti1x  why is this needed ? Would we not want to keep the styles ?

**Comment by unti1x** [comment]
This fix forces bbforms to use standard bs3 css class for bs3 version instead of bs2

**Comment by exussum12** [comment]
Looking at the docs. Should this class not be applied to the parent ?

**Comment by exussum12** [comment]
is this a duplicate of  #454 ?

**Comment by unti1x** [comment]
This class should be applied to the parent. It removes ul's bullets from checkbox lists. It's not duplicate of #454.

**Comment by glenpike** [comment]
@exussum12 @unti1x  can you look at the version on my branch where I've resolved the merge conflict with #454 - 35cda11

I've also also added examples to the test page and added a field for the radio buttons which should fix issues, but please can you review and we can get all the fixes in?

**Comment by glenpike** [comment]
(Will also need to rebuild scripts)

**Comment by unti1x** [comment]
Merged and fixed. `Form.editors.Checkboxes.prototype.className` and `Form.editors.Radio.prototype.className` should be `'list-unslyled'` because they are lists and `Form.editors.Checkboxe.prototype.className` is just item so it's `'checkbox'`

**Comment by glenpike** [comment]
Sorry, I'm not 100% happy with this - it may be right according to the Bootstrap doc's, but it looks incorrect in the browser.

If you merge this patch with my branch https://github.com/glenpike/backbone-forms/tree/unti1x-patch-1 and resolve the conflict in favour of your commit, viewing the ./examples/register-form-custom-template/index.html in a browser (need to serve from backbone-forms root) you will see that the result doesn't look correct.

Are you happy try merging that branch into your's or updating your code / adding some checkboxes/radio's to the examples and getting the result looking good?

**Comment by glenpike** [comment]
Fixed with #532

**Pull request closed without merging**
