### PR TITLE
Add Tests for #433 - external nestedField template

### PR DESCRIPTION
**Pull request by glenpike**

### CODE REVIEW

**Comment by exussum12** [comment]
Changes to dist (can cause conflicts later)

**Comment by glenpike** [comment]
Damn - I thought I'd managed to revert the changes to dist - will recheck that.

**Comment by glenpike** [comment]
Okay - think this is all reverted.  It's strange - the minified files seemed fine as opposed to the plain ones - can you just verify this if possible?

**Comment by exussum12** [comment]
Looks good. Merging

**Pull request merged**
