### PR TITLE
 Package release dates added to README.md

### PR DESCRIPTION
**Pull request by nareshv**
Updated README.md to reflect the version releases.

Release version is taken from /releases page

### CODE REVIEW

**Comment by exussum12** [comment]
What benefit is this ?

**Comment by glenpike** [comment]
I'm not sure that this adds anything useful to the project, but I think we should consider making "releases" a bit more documented using the features on Github to do so - if you look at Bootstrap's [Release page](https://github.com/twbs/bootstrap/releases), this contains a lot of useful information.  Maybe we can tag 0.14.1 as a fix for the bower version issue and then use that to draft a release?

**Comment by nareshv** [comment]
This idea is from [Changelog](https://en.wikipedia.org/wiki/Changelog) files, which keep track of major things accomplished in chronological order. Which is followed by many opensource projects.

Another way to achieve the same thing is to tag a version like its described by @glenpike

**Comment by glenpike** [comment]
I'm going to close this as I would favour using the releases page more.

**Pull request closed without merging**
