### PR TITLE
Max Cardinality in Lists + Unit Tests

### PR DESCRIPTION
**Pull request by glenpike**
Merge in #444, refactor duplication and add unit tests.

### CODE REVIEW

**Comment by exussum12** [comment]
Hmmm not sure about the wording, from a mahts/database background carnality is the unique values 

https://i.ytimg.com/vi/K8whYBarK8M/hqdefault.jpg

where as this is the total values ?

**Comment by glenpike** [comment]
Rename to "maxListLength" ?

**Comment by exussum12** [comment]
Sounds good to me :)

**Comment by glenpike** [comment]
Done

**Comment by exussum12** [comment]
Looks great :) Cheers

**Pull request merged**
