### PR TITLE
Number in range validator

### PR DESCRIPTION
**Pull request by fonji**
Hello,

I created a range validator. I think it may be usefull to include it in the library.

Please note that I **changed the number validator's regexp**, so it accepts negative values, forces to have at least one decimal number (refuses ".") and refuses if there's no value after a decimal point (such as "0.").
Downside is: it will refuse the scientific input ".5" (but will accept "0.5").
I based my regexp from the one in the [MDN's parseFloat documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat#A_stricter_parse_function).
Tests have been updated accordingly.

Please let me know if you need anything else.
Have a nice day!

### CODE REVIEW

**Comment by glenpike** [comment]
@fonji, what about this one for numbers:

/[-+]?([0-9]*\.[0-9]+|[0-9]+)/

From http://www.regular-expressions.info/floatingpoint.html

That seems to work with ".5" and "1." and negative numbers?

If you want to update your pull request / tests, I'd be happy to merge that (I know it's been ages).

**Comment by fonji** [comment]
Here you go. I added ```^``` and ```$``` to the regexp, which results in ```/^[-+]?([0-9]*.[0-9]+|[0-9]+)$/```.
Tests pass successfully on firefox and chromium.

(no problem for the latency, thank you very much to make this project alive again)

**Comment by exussum12** [comment]
@fonji  there are conflicts are you able to resolve ?

**Comment by fonji** [comment]
There you go. I (stupidly) thought that the conflicts were only on distribution files and that it wasn't a big deal.
In the end it was just on lines my editor cleared (e.g. spaces at the end of the line).
I merged with master and rebuilt distribution files.

**Comment by glenpike** [comment]
Thanks :+1:

**Pull request merged**
