### PR TITLE
Solve list validated nested models #483

### PR DESCRIPTION
**Pull request by exussum12**
No tests added yet, Would prefer to know its solved the issue first

### CODE REVIEW

**Comment by exussum12** [comment]
@glenpike  Test added, could you take a look ?

**Comment by glenpike** [comment]
Hi, it looks like there maybe some other tests failing around that - 437, 438, 440.  Maybe it's because the schema is different for the tests?

**Comment by exussum12** [comment]
Updated it apologies

**Comment by glenpike** [comment]
Okay, those tests are fine.  440 seems to fail every other time, which is strange, so maybe we can look at that separately :+1:

**Pull request merged**
