### PR TITLE
update email regex to meet RFC 5322 requirements

### PR DESCRIPTION
**Pull request by rafaelmaza**
regex borrowed from http://www.regular-expressions.info/email.html, previous regex wouldn't allow valid (and somewhat common) emails like brian.o'connel@mail.com.

redoing changes from PR #478 into the correct file

### CODE REVIEW

**Comment by glenpike** [comment]
Would be nice to see some extra email tests for this if possible.  Is that something you are able to do?

See https://github.com/powmedia/backbone-forms/blob/master/test/validators.js#L180 - are there any more email addresses we can add to the valid / invalid tests?

**Comment by glenpike** [comment]
Thanks!

**Comment by glenpike** [comment]
Hi, I've got some failing tests on this one:

'fails invalid emails' is failing on:

foo/bar@example.com
foo?bar@example.com

Could you please have a look at the tests / regex if possible?

**Comment by exussum12** [comment]
They are both valid according to 
http://stackoverflow.com/a/2049510

**Pull request merged**
